[theme]
primaryColor = "#000000"             # Black buttons (Premium)
backgroundColor = "#FFFFFF"          # White background
secondaryBackgroundColor = "#F5F5F5" # Light Grey Sidebar (No more blue)
textColor = "#262730"                # Dark Grey text
font = "sans serif"